version: "3.9"

name: "coredns"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE_NAME: coredns
        PACKAGE_GIT_REF: ""
        PACKAGE_VERSION: 1.10.0
        PACKAGE_VERSION_PREFIX: "v"
        PACKAGE_URL: https://github.com/coredns/coredns
        PACKAGE_SOURCE_URL: https://github.com/coredns/coredns/archive/v1.10.0.tar.gz
        PACKAGE_HEAD_URL: https://github.com/coredns/coredns.git
        PACKAGE_HEAD: false
        GIT_CLONE_FLAGS: ""
        CACHEBUST: https://api.github.com/repos/issenn/docker-images-coredns/git/refs/heads/master
        GO111MODULE: on
        GOPROXY: https://proxy.golang.org,direct
        CGO_ENABLED: 0
        BUILD_FLAGS: "-v"
