---

name: Test

on:
  push:
    paths:
      - "renovate.json5"
  workflow_dispatch:

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/tmp
          cat <<EOF > ~/tmp/my-secret1-in-file
          ${{ secrets.FLOWZONE_TOKEN}}
          EOF
          cat <<EOF > ~/tmp/my-secret2-in-file
          ${{ secrets.GHCR_TOKEN}}
          EOF
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-secrets
          path: ~/tmp/
